### PR TITLE
added fadeOut on error messages

### PR DESCRIPTION
**Pull request by hyptos**
There is a 3s delay. Is this working for you ?

### CODE REVIEW

**Comment by prabhakar267** [comment]
I think instead of fading out we can clear out ```#errors``` div on every button submit

**Comment by hyptos** [comment]
now it's on every submit event

**Comment by prabhakar267** [comment]
@hyptos Changes look fine, can you squash the changes into 1 commit

**Comment by prabhakar267** [comment]
Squashed and Merged! 
28fdb2376d485245da6e335e1328c847906e2e18

**Pull request closed without merging**
