### PR TITLE
Check for files on submission

### PR DESCRIPTION
**Pull request by Pro-Ice**
Fixes for prabhakar267/WA-Reader#14. Added a separate function on form submission to better separate that from file upload handling itself.

### CODE REVIEW

**Comment by prabhakar267** [comment]
@Pro-Ice Can you please change the PR just for 05477a186313770755689d5d063e9be11984b1aa
Code change looks fine to me

**Comment by Pro-Ice** [comment]
I've merged with remote and fixed the merge conflict that way. I'm worried I might break it again if I try squashing everything in my branch, maybe the better option would be [squash merging](https://github.com/blog/2141-squash-your-commits) the pull request on GitHub?

**Comment by prabhakar267** [comment]
I don't want to add a merge commit when it is not necessary! You can follow the following steps, you correct this situation
+ Bring your master to sync with source-master
```git checkout master```
```git pull origin master```
+ Make a new branch from master for the fix
```git checkout -b check-file-submission-fix```
+ Cherry-pick your commit
```git cherry-pick 05477a186313770755689d5d063e9be11984b1aa```

Now your branch "check-file-submission-fix" would have 05477a186313770755689d5d063e9be11984b1aa on top of all the commits. You can either raise a new PR from that branch or you can bring your current branch ```form-submit-check``` in sync with ```check-file-submission-fix```

**Comment by Pro-Ice** [comment]
Thank you so, so much for the extensive comment. This helped me learn a lot about git.

After stumbling on merge commits in my master for a while, this branch is now clean and mergeable. =]

**Pull request merged**
