### PR TITLE
Fix #28 and #50: ZIP upload support

### LINKED ISSUE #28: Add images support for conversations with "media attached" (Provide an upload zip option)
Hi,

is it possible to add photos in the reader?

### PR DESCRIPTION
**Pull request by uptoratlen**
Hi,

again me...
The last fix for the parser was actually the result of this larger enhancement....so here is the main part.
As a relative passed away some weeks ago, I was asked how to archive the chats of that ios phone, preferred in such way to not only see the text but also media like images and videos.
WA Reader looks like a perfect start. Small and locally installable on my server (no cloud or other stuff to hand over private chats).
But as seen in issue #28 and issue #50, it lacks the support since some years.
After my journey started I think I now know why you did not added this in first place. Over time the WA exports changed and they made it also language depended :-( (eg. you will see in my sample German text). And sometimes I get a zip (iOs) and sometimes I get single files in case I export a chat. To be fully independent I tried my best but will be a long way. So let me explain a bit:

A zip is expected to have no subfolders, the CHAT file is expected to be named "_chat.txt" (I will enhance the app.py later to find the chat file automatic). The file is uploaded and extracted to "static/chat", the folder will be cleared in next run. Not the best, but as I intend to run it locally, I got no fear of privacy. But on a public server like the demo server it may need a re-design. (aka help)

The the magic happens in script.js. A new response is handed over to signal possible attachments are seen, otherwise the "old" logic will be used.  Than some regexp tried to extract the filename of the attachment. As said, I tried it with iOs and Android. Both working but more samples from the "world" would be helpful. (or is there a doc of WA exports?).
Based on some supported file extensions the new div tags are filled (video, audio...), this should also offer some controls in the page. As a nice bonus, images will be resized if you hover over it.

To allow you to check my code proposal I also added a ZIP in the samples folder (Chat_Sample.zip). I added a local recorded audio, video and photo. Crossing fingers that it will work.

I don't expect you to come back in 5 minutes with a merge this time. Take your time, but maybe this enhances WA reader a bit more.  You will also see in the code still some remarks about assumptions(I think), this could be gaps or worse.
At least I already got positive feedback from my "customer". They already like it even it may not get re-merged to the main project .

And of course I want to mention: Please discus any line or design. I'm open to change as far as I able to do so (let's say 1 day ago I coded .js first time since ~ 15 years).

Have a nice weekend

### CODE REVIEW

**Comment by uptoratlen** [comment]
Hi, 
I thought it might be a good idea to demo the change in a video. So I recorded the run. First I open the existing sample to show it did not harm the existing and than I upload the ZIP sample file. But see for your self. 

https://user-images.githubusercontent.com/80213345/120071223-8f7aa280-c08e-11eb-979d-08a109382638.mp4

cu

**Comment by uptoratlen** [comment]
Maybe I should demo the change. Here is what it looks like in my run.
(I open the sample text chat only to show the existing function is not changed)

https://user-images.githubusercontent.com/80213345/120073448-a2927000-c098-11eb-8996-74a654843d32.mp4

**Comment by prabhakar267** [comment]
@uptoratlen Firstly thanks for the support, this has been long pending. I'm working on verifying your code, it will take some time for me to fully verify. 
Please bear with me

**Review by prabhakar267 — APPROVED** [review]
@uptoratlen there are some minor changes that needs to happen. 
I'm approving this PR since I anyways had to make some changes to the code.
Thanks for resolving this.

**Comment by uptoratlen** [comment]
Thx, the upload is ok for local installations. While you reviewed this. I also came up with some security issues. Like path of attachments. But I think there is also some kind of sanitiser lib we could use. I will open a new issue for this. Thx for the merge.

**Pull request merged**
